[package]
name = "fifo_bounded_buffer"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["lib"]
path = "src/queue.rs"

[dependencies]
clap = { version = "4.5.36", features = ["derive"] }
rand = "0.9.0"
